Overhaul approval method configuration
You now configure the route53 method with named parameters like this:

    example.com. route53 aws_access_key_id=AKIA... aws_secret_access_key=a9MX...

Other valid parameters are aws_credentials_profile and hosted_zone_id.
All parameters are optional.  If you omit a parameter, the method will
attmept to do the right thing, for example by pulling credentials out
of ~/.aws/credentials.

diff --git a/libexec/sslmate/approval/http/documentroot b/libexec/sslmate/approval/http/documentroot
--- a/libexec/sslmate/approval/http/documentroot
+++ b/libexec/sslmate/approval/http/documentroot
@@ -52,9 +52,9 @@ hostname=$2
 path=$3
 contents=$4
 
-if [ $NUM_PARAMS != 1 ]
+if [ $PARAMS != "0" ]
 then
-	echo "documentroot: Error: unexpected number of parameters (got $NUM_PARAMS, expected 1)" >&2
+	echo "documentroot: Error: unexpected parameters (expected exactly 1 parameter)" >&2
 	exit 2
 fi
 
